// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// IMPORTANT: This is a template file. You need to run:
/// ```
/// flutterfire configure
/// ```
/// to generate the actual configuration with your Firebase project details.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3y2zq7Hopec0c1xHztZDaBb8hN9iq1eQ',
    appId: '1:82223674346:web:22b4bbd64c18ac3c3ef893',
    messagingSenderId: '82223674346',
    projectId: 'hari-portfolio-9cd93',
    authDomain: 'hari-portfolio-9cd93.firebaseapp.com',
    storageBucket: 'hari-portfolio-9cd93.firebasestorage.app',
    measurementId: 'G-RJWB2QKR3Q',
  );

  // TODO: Replace with your actual Firebase Web configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk75SlLTRc5Di1_O7ldCaznQK57sgPuY8',
    appId: '1:82223674346:android:589419cda74e3f893ef893',
    messagingSenderId: '82223674346',
    projectId: 'hari-portfolio-9cd93',
    storageBucket: 'hari-portfolio-9cd93.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase Android configuration

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHgBWzLRllfy-V_vy2Hr2bFWdrBRY3RSk',
    appId: '1:82223674346:ios:66e3e25b147112d23ef893',
    messagingSenderId: '82223674346',
    projectId: 'hari-portfolio-9cd93',
    storageBucket: 'hari-portfolio-9cd93.firebasestorage.app',
    iosBundleId: 'com.example.haiPortfolio',
  );

  // TODO: Replace with your actual Firebase iOS configuration

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHgBWzLRllfy-V_vy2Hr2bFWdrBRY3RSk',
    appId: '1:82223674346:ios:66e3e25b147112d23ef893',
    messagingSenderId: '82223674346',
    projectId: 'hari-portfolio-9cd93',
    storageBucket: 'hari-portfolio-9cd93.firebasestorage.app',
    iosBundleId: 'com.example.haiPortfolio',
  );

  // TODO: Replace with your actual Firebase macOS configuration

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3y2zq7Hopec0c1xHztZDaBb8hN9iq1eQ',
    appId: '1:82223674346:web:f775646e5ea419823ef893',
    messagingSenderId: '82223674346',
    projectId: 'hari-portfolio-9cd93',
    authDomain: 'hari-portfolio-9cd93.firebaseapp.com',
    storageBucket: 'hari-portfolio-9cd93.firebasestorage.app',
    measurementId: 'G-FFT5RJ1EYG',
  );

  // TODO: Replace with your actual Firebase Windows configuration
}
